<?php
	$client_id = $this->getClientId();
	$endpoint = $this->getEndPoint();
	$client_salesmanago_id = $this->getClientSalesManagoId();
	$additional_js = $this->getAdditionalJs();
	$active = $this -> isActive();

if($active == 1 && !empty($client_id) && !empty($endpoint)){
	$trackingScript = "<script type='text/javascript'>\n";
	$trackingScript .= "\tvar _smid = '".$client_id."';\n";
	if(isset($additional_js) && !empty($additional_js)){
		$trackingScript .= "\t".$additional_js."\n";
	}
	if($client_salesmanago_id){
		$trackingScript .= "\tvar _smclientid = '".$client_salesmanago_id."';\n";
	}
	$trackingScript .= "\t(function(w, r, a, sm, s ) {\n";
	$trackingScript .= "\t\tw['SalesmanagoObject'] = r;\n";
	$trackingScript .= "\t\tw[r] = w[r] || function () {( w[r].q = w[r].q || [] ).push(arguments)};\n";
	$trackingScript .= "\t\tsm = document.createElement('script'); sm.type = 'text/javascript'; sm.async = true; sm.src = a;\n";
	$trackingScript .= "\t\ts = document.getElementsByTagName('script')[0];\n";
	$trackingScript .= "\t\ts.parentNode.insertBefore(sm, s);\n";
	$trackingScript .= "\t\t})(window, 'sm', ('https:' == document.location.protocol ? 'https://' : 'http://') + '".$endpoint."/static/sm.js');\n";
	$trackingScript .= "</script>\n";

	echo $trackingScript;
}
?>
